# Makefile for GNU make

.PHONY: all 26_toon_shading .DEFAULT 

UNAME := $(shell uname)

all: 26_toon_shading 

26_toon_shading:
	$(MAKE) -f Makefile.26_toon_shading 26_toon_shading

.DEFAULT:
	$(MAKE) -f Makefile.26_toon_shading $@

