# Makefile for GNU make

.PHONY: all 12_light_attenuation .DEFAULT 

UNAME := $(shell uname)

all: 12_light_attenuation 

12_light_attenuation:
	$(MAKE) -f Makefile.12_light_attenuation 12_light_attenuation

.DEFAULT:
	$(MAKE) -f Makefile.12_light_attenuation $@

