# Makefile for GNU make

.PHONY: all 23_bump_map_floor .DEFAULT 

UNAME := $(shell uname)

all: 23_bump_map_floor 

23_bump_map_floor:
	$(MAKE) -f Makefile.23_bump_map_floor 23_bump_map_floor

.DEFAULT:
	$(MAKE) -f Makefile.23_bump_map_floor $@

