# Makefile for GNU make

.PHONY: all 13_spotlight .DEFAULT 

UNAME := $(shell uname)

all: 13_spotlight 

13_spotlight:
	$(MAKE) -f Makefile.13_spotlight 13_spotlight

.DEFAULT:
	$(MAKE) -f Makefile.13_spotlight $@

