# Makefile for GNU make

.PHONY: all 11_two_lights_with_structs .DEFAULT 

UNAME := $(shell uname)

all: 11_two_lights_with_structs 

11_two_lights_with_structs:
	$(MAKE) -f Makefile.11_two_lights_with_structs 11_two_lights_with_structs

.DEFAULT:
	$(MAKE) -f Makefile.11_two_lights_with_structs $@

